config/routes.rb
Rails.application.routes.draw do
  resources :invoices do
    resources :purchases, except: [:index], controller: 'invoices/purchases'
  end

  resources :employees
  resources :companies do
    collection { post :import }
  end

  devise_for :users
  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/faqs'

  get 'pages/pricing'

  get 'pages/features'

  root 'pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvoiceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About Us", pages_about_path %></li>
			<li><%= link_to "Contact", pages_contact_path %></li>
			<li><%= link_to "Features", pages_features_path %></li>
			<li><%= link_to "FAQs", pages_faqs_path %></li>

			<% if current_user %>

				<div class="btn-group pull-right right-nav">
					<button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">Admin 
						<span class="caret"></span>
						<span class="sr-only">Admin</span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to "Invoices", invoices_path %></li>
						<li><%= link_to "Employees", employees_path %></li>
						<li><%= link_to "Companies",
							companies_path %></li>
					</ul>
				</div>
				<li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<li class="pull-right"><%= link_to edit_user_registration_path do %><%= current_user.email %><% end %></li>					
			<% else %>
				<li class="pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
				<li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
			<% end %>
		</ul>
		
		<% if flash[:notice] %>
			<div class="alert alert-success alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= notice %>
			</div>
		<% elsif flash[:error] %>
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dissmiss="alert" aria-label="Close"><span aria=hidden="true">&times;</span></button>
				<%= error %>				
			</div>
		<% elsif flash[:alert] %>
			<div class="alert alert-warning alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= alert %>				
			</div>	
		<% end %>

	
		<%= yield %>

	</div><!--/.container-->

</body>
</html>